org.gradle.jvmargs=-Xmx3172M

minecraft_version=1.21.9
supported_versions=
yarn_mappings=1.21.9+build.1
enabled_platforms=fabric,neoforge

archives_base_name=midnightlib
mod_version=1.8.2
maven_group=eu.midnightdust
release_type=release
curseforge_id=488090
modrinth_id=codAaoxh

fabric_loader_version=0.17.2
fabric_api_version=0.133.14+1.21.9

neoforge_version=21.9.3-beta
yarn_mappings_patch_neoforge_version = 1.21+build.4

mod_menu_version = 9.0.0